name: Test Coverage of master branch

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  coverage-master:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
      - name: Test coverage for master
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
          npm run coverage
          cp "${{github.workspace}}/coverage/merged/lcov.info" "${{github.workspace}}/coverage/lcov.info"
          ./cc-test-reporter after-build --debug --exit-code $?
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          GIT_BRANCH: ${{ github.base_ref }}
